var TITLE = "【FATE】泥偶的伊碧娜";
var INDEX = [
	{ title: "團務區", url: "https://docs.google.com/spreadsheets/d/1HuWlGaaZp_4SYOuKywDCXSKdn21BAhPICJsinZCrCDI/edit?usp=sharing", },
	{ title: "山嵐之年", url: "伊碧娜00.html", },
	{ title: "雨驟風狂", url: "伊碧娜01.html", },
	{ title: "暮落驚雷", url: "伊碧娜02.html", },
	{ title: "雨寂泉流", url: "伊碧娜03.html", },
	{ title: "薩滿新世代", url: "伊碧娜03-5.html", },
	{ title: "聲息", url: "伊碧娜04.html", },
	{ title: "克蒙阿朵堂", url: "伊碧娜4.5.html", },
	{ title: "狼嚎", url: "伊碧娜05.html", },
	{ title: "追亡逐北", url: "伊碧娜5.5.html", },
	{ title: "烏札的領袖們", url: "伊碧娜06.html", },
	{ title: "決心", url: "伊碧娜07.html", },
	{ title: "聖三巫", url: "伊碧娜08.html", },
	{ title: "格古拉之夜", url: "伊碧娜09.html", },
	{ title: "盟約者們", url: "伊碧娜10.html", },
	{ title: "殞落", url: "伊碧娜11.html", },
	{ title: "夜宴", url: "伊碧娜12.html", },
	{ title: "歸於黑暗", url: "伊碧娜13.html", },
	{ title: "拂曉", url: "伊碧娜14.html", },
	{ title: "烈陽閃焰", url: "伊碧娜15.html", }, 
	{ title: "薪火", url: "伊碧娜16.html", }, 
	{ title: "葬禮", url: "伊碧娜17.html", }, 
	{ title: "執著", url: "伊碧娜18.html", }, 
	{ title: "驕陽", url: "伊碧娜19.html", }, 
	{ title: "降生", url: "伊碧娜20.html", }, 
	{ title: "晦暗之夜", url: "伊碧娜21.html", }, 
	{ title: "雨霽", url: "伊碧娜22.html", }, 
	{ title: "創傷", url: "伊碧娜23.html", }, 
	{ title: "肅穆的領袖們", url: "伊碧娜24.html", }, 
	{ title: "夜、星、夢", url: "伊碧娜25.html", }, 
	{ title: "破裂", url: "伊碧娜26.html", }, 
];
