var TITLE = "【DRYH】Harbour";
var INDEX = [
	{ title: "團務區", url: "https://docs.google.com/spreadsheets/d/1stBqzTID3fc3sKMyVVk7wJKIKEfyilxk19EA1R8JPQU/edit#gid=608821430", },
	{ title: "01：腐巢", url: "【ＤＲＹＨ】Harbour-chapter1.html", },
	{ title: "幕間01", url: "【ＤＲＹＨ】Harbour-chapter1.5.html", },
	{ title: "02：隙間", url: "【ＤＲＹＨ】Harbour-chapter2.html", },
	{ title: "幕間02", url: "【ＤＲＹＨ】Harbour-chapter2.5.html", },
	{ title: "03：磐石", url: "【ＤＲＹＨ】Harbour-chapter3.html", },
	{ title: "幕間03", url: "【ＤＲＹＨ】Harbour-chapter3.5.html", },
	{ title: "04：命運", url: "【ＤＲＹＨ】Harbour-chapter4.html", },
	{ title: "幕間04", url: "【ＤＲＹＨ】Harbour-chapter4.5.html", },
	{ title: "05：風雲", url: "【ＤＲＹＨ】Harbour-chapter5.html", },
	{ title: "幕間05", url: "【ＤＲＹＨ】Harbour-chapter5.5.html", },
	{ title: "06：失落", url: "【ＤＲＹＨ】Harbour-chapter6.html", },
	{ title: "07：現實", url: "【ＤＲＹＨ】Harbour-chapter7.html", },
	{ title: "幕間07", url: "【ＤＲＹＨ】Harbour-chapter7.5.html", },
	{ title: "08：命運復歸", url: "【ＤＲＹＨ】Harbour-chapter8.html", },
	{ title: "幕間08", url: "【ＤＲＹＨ】Harbour-chapter8.5.html", },
	{ title: "09：風雲復歸", url: "【ＤＲＹＨ】Harbour-chapter9.html", },
	{ title: "幕間09", url: "【ＤＲＹＨ】Harbour-chapter9.5.html", },
	{ title: "10：命運再臨", url: "【ＤＲＹＨ】Harbour-chapter10.html", },
];
